spring:
  # Quartz 的配置，对应 QuartzProperties 配置类
  quartz:
    # 将任务等保存化到数据库
    job-store-type: jdbc
    jdbc:
      initialize-schema: never

  # DataSource Config
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://172.16.2.10:3306/tauren?characterEncoding=UTF-8&useInformationSchema=true
    username: root
    password: 3eCrAw8Ba6Tg
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      maximum-pool-size: 100
      minimum-idle: 10
      idle-timeout: 300000
      max-lifetime: 1800000
      connection-timeout: 30000
      auto-commit: true
      connection-test-query: SELECT 1
      pool-name: DatebookHikariCP

logging:
  level:
    org.springframework: info
    org.springframework.security: info
    web: info

springdoc:
  api-docs:
    enabled: true

application:
  security:
    jwt:
      secret-key: 586B633834416E396D7436753879382F423F4428482B4C6250655367566B5970
      expiration: 28800000 #  8h in ms
      refresh-token:
        expiration: 1296000000 # 15 days in ms